version: "3.8"
services:
  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus/:/etc/prometheus
      - ./data/prometheus/:/prometheus/
    command: "--config.file=/etc/prometheus/prometheus.yml --storage.tsdb.path=/prometheus"
    ports:
      - 9090:9090
  grafana:
    image: grafana/grafana
    volumes:
      - ./data/grafana/:/var/lib/grafana
      - ./grafana/:/etc/grafana/provisioning/
    ports:
      - 3000:3000
    depends_on:
      - prometheus
  node-exporter:
    image: prom/node-exporter
    volumes:
      - /:/rootfs:ro
    ports:
      - 9100:9100
  